FORMAT: 1A

# Majestic Thai

## Menu [/dishes]

### Dish List [GET]

+ Request (/dishes)

    [
        {
            _id: "5812857aa7825e0003b9961d",
            name: "Salmon Fried Rice",
            description: "Thai style fried rice with Salmon, eggs, onions, pease, etc",
            price: 13.95
        },
        {
            _id: "5812857aa7825e0003b9961c",
            name: "Fried Rice",
            description: "Thai style fried rice with your choice of meat, eggs, onions, peas, etc",
            price: 9.95
        },
        {
            _id: "5812857aa7825e0003b9961b",
            name: "Rad Na",
            description: "Stir fried rice noodle mixed black bean sauce, with choice of meat",
            price: 10.5
        },
        {
            _id: "5812857aa7825e0003b9961a",
            name: "Silver Noodle",
            description: "Glass noodles, pan friend with eggs, carrots, mushroom and cabbage",
            price: 10.5
        },
        {
            _id: "5812857aa7825e0003b99619",
            name: "Pad Se Ew",
            description: "Stir fried with fresh wide rice noodles, broccoli, and eggs",
            price: 10.5
        },
        {
            _id: "5812857aa7825e0003b99618",
            name: "Chow Mein",
            description: "Stir fried with yellow rounded nooldes with vegetables",
            price: 10.5
        },
        {
            _id: "5812857aa7825e0003b99617",
            name: "Pad Kee Mao",
            description: "Hot and spicy stir fried sphagetti with eggs, garlilc, etc",
            price: 10.5
        },
        {
            _id: "5812857aa7825e0003b99616",
            name: "Orange Chicken",
            description: "Deep fried chicken sauteed in a tangy orange sauce",
            price: 10.5
        },
        {
            _id: "5812857aa7825e0003b99615",
            name: "Half Moon Tons",
            description: "Crab meat and cream cheese, wrapped in wonton",
            price: 7.95
        },
        {
            _id: "5812857aa7825e0003b99614",
            name: "Thai Iced Tea",
            description: "Delicious cold beverage with thai tea and half and half",
            price: 3
        }
    ]

## Menu Item [/dishes/{id}]


### List Dish ID [GET]

+ Request (dishes/{id})

    [
        {
            _id: "5812857aa7825e0003b9961d",
            name: "Salmon Fried Rice",
            description: "Thai style fried rice with Salmon, eggs, onions, pease, etc",
            price: 13.95
        }
    ]
    
## Listing of Orders [/orders]

###List of Orders [GET]

+ Request (/orders)

    [
        { _id: 5812857aa7825e0003b9933,
        name: "Peter",
        price: 34.4
        
            {
                _id: "5812857aa7825e0003b9961d",
                name: "Salmon Fried Rice",
                description: "Thai style fried rice with Salmon, eggs, onions, pease, etc",
                price: 13.95
            },
            {
                _id: "5812857aa7825e0003b9961c",
                name: "Fried Rice",
                description: "Thai style fried rice with your choice of meat, eggs, onions, peas, etc",
                price: 9.95
            },
            {
                _id: "5812857aa7825e0003b9961b",
                name: "Rad Na",
                description: "Stir fried rice noodle mixed black bean sauce, with choice of meat",
                price: 10.5
            }
        },
        { _id: 5812857aa7825e0003b9933,
        name: "Kevin",
        price: 34.4
        
            {
                _id: "5812857aa7825e0003b9961d",
                name: "Salmon Fried Rice",
                description: "Thai style fried rice with Salmon, eggs, onions, pease, etc",
                price: 13.95
            },
            {
                _id: "5812857aa7825e0003b9961c",
                name: "Fried Rice",
                description: "Thai style fried rice with your choice of meat, eggs, onions, peas, etc",
                price: 9.95
            },
            {
                _id: "5812857aa7825e0003b9961b",
                name: "Rad Na",
                description: "Stir fried rice noodle mixed black bean sauce, with choice of meat",
                price: 10.5
            }
        }
    ]

## Create a Order ID [/orders/3]

### Order ID [/orders/3]

+ Request (/order/3)

    [
        {   _id: 5812857aa7825e0003b9933,
            username: "Peter",
            total: 34.4,
            "published_at": "2016-11-11T08:40:51.620Z"
            {
                _id: "5812857aa7825e0003b9961d",
                name: "Salmon Fried Rice",
                description: "Thai style fried rice with Salmon, eggs, onions, pease, etc",
                price: 13.95
            },
            {
                _id: "5812857aa7825e0003b9961c",
                name: "Fried Rice",
                description: "Thai style fried rice with your choice of meat, eggs, onions, peas, etc",
                price: 9.95
            },
            {
                _id: "5812857aa7825e0003b9961b",
                name: "Rad Na",
                description: "Stir fried rice noodle mixed black bean sauce, with choice of meat",
                price: 10.5
            }
        }
    ]